LUN-22: Вёрстка меню
Lunatics-yp/lunatics pull request #15
Opened 2023-03-30 16:14 UTC by djpont

> Запускать проект командой: `yarn run dev:client`
> Главное меню игры доступно по ссылке: http://localhost:3000/mainmenu

[Ссылка на задачу в Linear](https://linear.app/lunatics/issue/LUN-22/vyorstka-igrovogo-menyu)
Меню, которое видит игрок перед запуском игры.
Несколько слоёв меню с кнопками.
Главное:
 - Играть против ИИ
 - Играть онлайн
 - Мой профиль
 - Правила игры
 - Настройки
 - Форум
 - Авторы
 - Выйти
Играть против ИИ:
 - Выбор сложности ИИ
 - Выбор режима игры (если будет несколько)
 - Кнопки "Назад" и "Играть"
Играть онлайн:
 - Поиск соверника по нику (тут нужно отдельно подумать как коннект в онлайне будет)
 - Или тут же сделать лобби с выбором активных игроков
 - Выбор режима игры (если будет несколько)
 - Кнопки "Назад" и "Играть"
Играть:
 - Расстановка своих кораблей (не уверен, что это в рамках текущего спринта)
Настройки:
 - Сменить язык
 - Громкость звуков и музыки (если будет)
 - Кнопка "Назад"

Макет:
<img width="573" alt="image" src="https://user-images.githubusercontent.com/34692754/228898288-97c3c2ad-880d-436d-8918-feb170fa8bd5.png">

Референсы:
<img width="1271" alt="image" src="https://user-images.githubusercontent.com/34692754/228898392-61655b72-5106-4bff-a953-91e6d8f3916d.png">
<img width="1272" alt="image" src="https://user-images.githubusercontent.com/34692754/228898425-d30f8495-f8ec-447b-b1d6-5174b60a4f70.png">

2023-03-30 18:20 UTC, yp-ivan approved these changes
В целом всё хорошо.

2023-03-30 18:20 UTC, yp-ivan commented on packages/client/src/components/Switch/typing.ts
> +import {Fn} from '../../types';
Лучше написать `client/src/types`

2023-03-30 19:11 UTC, Moriarty25 reviewed
Классная табличка!

2023-03-30 19:35 UTC, JennJs approved these changes

2023-03-30 19:47 UTC, IRGrekov approved these changes

2023-03-31 02:34 UTC, yp-ivan commented on packages/client/src/components/Switch/typing.ts
> +import {Fn} from '../../types';
Да, теперь всё ок!

2023-03-31 04:10 UTC, AntLer-24rus requested changes
Хороший ПР, в целом отлично проделанная работа. Есть некоторые шероховатости и вопросы по смешиванию "мух" с "котлетами" см. коментарии. Но в целом все консистентно и корректно. Единственное меня беспокоит что как-то странно у вас в репозитории работает приттер, местами видны проблемы которые обычно исправляются автоматически.

2023-03-31 04:10 UTC, AntLer-24rus commented on packages/client/src/pages/MainMenu/pages/playOnline/playOnline.module.scss
> +
Придирка, бросается в глаза больше одной пустой строки в конце фала. Проверь что у тебя локально запускается линтер и приттер при коммите.

2023-03-31 14:43 UTC, djpont commented on packages/client/src/components/PlayersList/index.tsx
> +				<Fragment key={key}>
Мне эти ключи не нужны, но реакт ругался, что если компонент возвращает массив компонентов, то у каждого компонента должен быть ключ. Потому просто добавил индекс.
Попробую решить иначе: добавить вокруг возвращаемого ещё один <Fragment />

2023-03-31 19:30 UTC, djpont commented on packages/client/src/components/PlayersList/index.tsx
> +				<Fragment key={key}>
Убрал key, ошибки нет, видимо не с этим была связана.

2023-03-31 19:33 UTC, djpont commented on packages/client/src/components/PlayersList/index.tsx
> +		return <>{lobbyDataItems}</>;
Не получилось, пишет ошибку:
```
TS2786: 'PlayersListTable' cannot be used as a JSX component.
  Its return type '{ lobbyDataItems: JSX.Element[]; }' is not a valid JSX element.
    Type '{ lobbyDataItems: Element[]; }' is missing the following properties from type 'ReactElement<any, any>': type, props, key
```
Потому что у меня там возвращается массив элементов, а JSX требует, чтобы у них был родитель.

2023-03-31 19:34 UTC, djpont commented on packages/client/src/main.tsx
> +]);
Роутер ещё не был полностью готов, с ближайшим коммитом будет исправлено

2023-03-31 19:36 UTC, djpont commented on packages/client/src/main.tsx
> +		<Background/>
Возможно у нас что-то не настроено. Я использую функцию Reformat Code в WebStorm, он по-умолчанию удаляет этот пробел. В файлике PlayersList, видимо, не запускал её))). Постараемся списаться в Пачке по поводу настройки eslint.

2023-03-31 19:40 UTC, djpont commented on packages/client/src/pages/MainMenu/pages/playOnline/playOnline.module.scss
> +
Добавил правила в eslint

2023-04-01 08:28 UTC, djpont commented on packages/client/src/components/PlayersList/playersList.module.scss
> +		background: var(--colorWhite);
Спасибо) Пришлось атрибуты использовать, т.к если использовать классы, то из-за scss modules нарушается вложенность. Как заставить scss modules хэшировать только "родительский" стиль в классе, не нашйл.

2023-04-01 08:37 UTC, djpont commented on packages/client/src/components/Switch/index.tsx
> +		looped = true
Спасибо! Нашёл правила для eslint и editorconfig, после мержа этого PR проведу рефакторинг всех файлов проекта.

2023-04-01 10:27 UTC, yp-ivan approved these changes
В целом хорошо.
По css не расписывал, но лучше использовать селекторы по классам (они более производительные).

2023-04-01 10:27 UTC, yp-ivan commented on packages/client/src/pages/MainMenu/pages/playAgainstAI/index.tsx
> +import {useState} from 'react';
Импорты из `react*`, возможно, лучше выносить наверх файла.
PATCHS также бы импортировал после импортов из реакта.
Примерно так:
```ts
import {useState} from 'react';
import {useNavigate} from 'react-router-dom';
import {PATHS} from 'client/src/routers/name';
// ниже остальные импорты
```

2023-04-01 10:27 UTC, yp-ivan commented on packages/client/src/routers/index.tsx
> +import {MainMenuSettings} from '../pages/MainMenu/pages/settings';
Лучше сделать импорт с абсолютным адресом, как для других компонентов.

2023-04-01 10:51 UTC, djpont commented on packages/client/src/pages/MainMenu/pages/playAgainstAI/index.tsx
> +import {useState} from 'react';
Делал ровно наоборот, ок, в телеге напишу про это утверждение

2023-04-01 11:00 UTC, djpont commented on packages/client/src/routers/index.tsx
> +import {MainMenuSettings} from '../pages/MainMenu/pages/settings';
Решил внутри компонента использовать относительные адреса импортов

2023-04-01 14:22 UTC, AntLer-24rus approved these changes
С моей стороны все ОК, работа проделана отличная! 💪 В качестве рекомендаций могу посоветовать подумать как деструктурировать сложную страницу на качу мелких компонентов, это пригодится в будущем.

2023-04-01 14:22 UTC, AntLer-24rus commented on packages/client/src/components/PlayersList/Table/index.tsx
Здесь `key` как пропс необходим, чтобы реакт мог отличать элементы массива друг от друга. Но я бы весь JSX  вынес в отдельный компонеyт `PlayerListItem` и уже его использовал как при мапинге массива.

2023-04-01 14:22 UTC, AntLer-24rus commented on packages/client/src/components/PlayersList/index.tsx
> +				<PlayersListTable data={data}/>
Смотрится уже лаконичней, можно и так оставить. или переделать аля:
```suggestion js
				{data.map((playerData, index) => (<PlayerListItem key={palyerData.id} playerData={playerData} idx={index} />))}				
```

Решать тебе

2023-04-01 14:24 UTC, djpont commented on packages/client/src/components/PlayersList/index.tsx
> +				<PlayersListTable data={data}/>
Неплохо, возьму на заметку! Спасибо!

2023-04-01 14:26 UTC, merged