Feature/lun 40 profile change info
Lunatics-yp/lunatics pull request #24
Opened 2023-04-03 20:25 UTC by IRGrekov

Доработка страницы профиля и написания запросов для изменения данных 

Изменения данных пользователя(пароль, аватар, логин, почту...)

2023-04-03 21:48 UTC, djpont commented on packages/client/src/api/profile.ts
> +type changePassword = {
Тип с буквы T называем: TChangePassword

2023-04-03 21:48 UTC, djpont commented on packages/client/src/api/profile.ts
> +
Тут тоже и пустую строчку хотелось бы убрать

2023-04-03 21:48 UTC, djpont commented on packages/client/src/api/profile.ts
> +export default {
Во всех модулях проекта мы экспортируем конкретную константу/класс с именем, давай такого правила везде придерживаться.
`export Profile { `

2023-04-03 21:48 UTC, djpont commented on packages/client/src/api/session.ts
> +			alert('500 error');
Лучше напечатать ошибку в консоль `console.error(error.response)` и выполнить `navigate` на страничку ошибки 500.

2023-04-03 21:48 UTC, djpont commented on packages/client/src/components/Avatar/Avatar.scss
> +@import "client/src/styles/app";
Кавычки не те. Проверь, подключен ли у тебя eslint к IDE.

2023-04-03 21:48 UTC, djpont commented on packages/client/src/components/Avatar/index.tsx
> +}) => {
Тут лучше деструктуризацию вынести в тело константы, мне так ревьювер советовал.

2023-04-03 21:48 UTC, djpont commented on packages/client/src/components/Avatar/typing.ts
> +export type AvatarProps = {
Тип пишем с буквы T `TAvatarProps`

2023-04-03 21:48 UTC, djpont commented on packages/client/src/pages/Profile/index.tsx
>  import './profile.scss';
Мы утвердили порядок импортов:
1. Сначала реакт
2. Затем paths
3. Затем другие компоненты
4. Затем локальные импорты внутри компонента

2023-04-03 21:48 UTC, djpont commented on packages/client/src/pages/Profile/index.tsx
> +							navigate('/profileChangePassword');
Адрес нужно вынести в PATH

2023-04-03 21:48 UTC, djpont commented on packages/client/src/pages/ProfileChangePassword/index.tsx
> +						navigate(-1);
Тут бы в роутер добавить проверку, если адреса -1 в истории нет, то куда-то переходить. Т.к. если пользователь на этой странице обновит страницу, то в -1 в истории роутера ничего не будет.

2023-04-04 05:10 UTC, yp-ivan reviewed
Есть замечания по коду (плюс те, что пальцем вверх отметил).
Есть изменения в `yarn.lock`, но нет изменений в файле `package.json`.

2023-04-04 14:00 UTC, djpont commented on lefthook.yml
> +    #     run: yarn stylelint
Нене, это я сам добавлял, чтобы yarn stylelint запускать. Не помню, чтобы я в  прекоммит это добавлял.

2023-04-04 15:51 UTC, Moriarty25 approved these changes
Старайся писать в наименовании коммитов помимо эмодзи еще и тип:
`feat: `

2023-04-04 16:56 UTC, djpont approved these changes

2023-04-04 16:56 UTC, djpont commented on packages/client/src/pages/Profile/index.tsx
> +			<Form className="form">
Кавычки

2023-04-04 17:04 UTC, JennJs approved these changes

2023-04-05 16:14 UTC, AntLer-24rus requested changes
Хорошая работа. Однако хочу заметить что в командной работе нужно немного более внимательно походить к тому какой код ты отдаешь команде. Поправь проблемные места и я готов выдать аппрув!

2023-04-05 16:14 UTC, AntLer-24rus commented on packages/client/src/api/session.ts
> +	response => response,
Вкусовщина, но я бы всегда оборачивал аргументы стрелочных функций в скобки. Ментально так проще воспринимать что происходит в строке.
```suggestion
	(response) => response,
```

2023-04-05 16:14 UTC, AntLer-24rus commented on packages/client/src/components/Avatar/index.tsx
> +		</label>
Хорошее решение со скрытым инпутом и лейблом для отлова клика! 🔥

2023-04-05 16:14 UTC, AntLer-24rus commented on packages/client/src/pages/Profile/index.tsx
> +	// };
Не стоит тащить такого рода комментарии в `dev` ветку. Захламляет код.

2023-04-05 16:14 UTC, AntLer-24rus commented on packages/client/src/pages/Profile/index.tsx
> +	});
Можно немного больше заморочиться и проверить в каком окружении запущен проект чтобы логин admin не попал на продакш. Обычно такой хардкод стреляет в самый неподходящий момент.

2023-04-05 16:14 UTC, AntLer-24rus commented on packages/client/src/pages/Profile/index.tsx
> +			<div></div>
Лишний `div`?

2023-04-05 16:14 UTC, AntLer-24rus commented on packages/client/src/pages/Profile/index.tsx
>  			<Header>Прифиль игрока</Header>
Опечатка
```suggestion
			<Header>Профиль игрока</Header>
```

2023-04-05 16:14 UTC, AntLer-24rus commented on packages/client/src/pages/Profile/index.tsx
> +				// onClick={onAvatarChange}
💩

2023-04-05 16:14 UTC, AntLer-24rus commented on packages/client/src/pages/Profile/index.tsx
> +	// const { login, email } = useSelector('из стора возьму данные пользователя')
💩

2023-04-05 16:14 UTC, AntLer-24rus commented on packages/client/src/pages/ProfileChangePassword/index.tsx
> +	// const { password } = useSelector('из стора возьму данные пользователя')
💩

2023-04-05 16:14 UTC, AntLer-24rus commented on packages/client/src/pages/ProfileChangePassword/index.tsx
> +		newPassword: ''
смотри комменты 👀

2023-04-05 16:14 UTC, AntLer-24rus commented on packages/client/src/pages/ProfileChangePassword/index.tsx
> +	console.log(passwords);
Видимо забытый отладочный кусочек кода

2023-04-05 16:14 UTC, AntLer-24rus commented on packages/client/src/pages/ProfileChangePassword/index.tsx
> +						navigate(-1);
Да все верно, можно например навигировать на домашнюю страницу. Если если у вас жесткая логика иерархии страниц и в профиль можно попасть только из одно места, захарткодит тут адрес откуда мы сюда попадаем

2023-04-05 16:14 UTC, AntLer-24rus commented on yarn.lock
Странно, нет никаких добавленных зависимостей в `package.json` а лок файл обновился. Посмотри внимательно что у тебя тут происходит. Возможно есть ошибка какая-то.

2023-04-06 06:29 UTC, IRGrekov commented on packages/client/src/pages/Profile/index.tsx
> +	// const { login, email } = useSelector('из стора возьму данные пользователя')
Добавил как до себя коммент, как нужно будет доделать после того как будет готова авторизация профиля

2023-04-06 06:29 UTC, IRGrekov commented on packages/client/src/pages/ProfileChangePassword/index.tsx
> +	// const { password } = useSelector('из стора возьму данные пользователя')
Добавил как до себя коммент, как нужно будет доделать после того как будет готова авторизация профиля

2023-04-06 06:30 UTC, IRGrekov commented on packages/client/src/pages/Profile/index.tsx
> +				// onClick={onAvatarChange}
Исправил это недоразумение, дописал запрос для смены аватарки

2023-04-06 06:32 UTC, IRGrekov commented on packages/client/src/pages/Profile/index.tsx
> +	});
Убрал входные данные для логина почти и текущего пароля, пока изменил на пустую строку, т.к пользователь не авторизован

2023-04-06 06:33 UTC, IRGrekov commented on packages/client/src/pages/Profile/index.tsx
> +	// };
Дописал функцию, срабатывающая при onChange

2023-04-06 14:58 UTC, AntLer-24rus commented on packages/client/src/pages/Profile/index.tsx
>  			<Header>Прифиль игрока</Header>
Так и не исправил опечатку =)

2023-04-06 15:46 UTC, merged