LUN-45: Реализация начала и завершения игры
Lunatics-yp/lunatics pull request #36
Opened 2023-04-14 13:43 UTC by JennJs

### Какую задачу решаем
Реализация начала и завершения игры

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2023-04-14 15:20 UTC, yp-ivan reviewed
Добавлю ссылку на vercel (почему-то автоматически ссылка не появилась):
https://lunatics-git-feature-lun-45-start-end-of-game-lunatics-yp.vercel.app/game

В целом хорошо, но есть мелкие замечания.

- Очень желательно не изменять файлы, которые непосредственно не касаются задачи.
- Стараться избегать инлайн-функций в jsx-коде.

2023-04-14 15:20 UTC, yp-ivan commented on packages/client/src/pages/Game/setShipsPage.tsx
> +				<Button text='Покинуть игру' onClick={() => navigate(PATHS.mainMenu)}/>
Думаю, здесь лучше развернуть каждый prop в отдельной строке (для единобразия и улучшения читабельности).

2023-04-14 15:20 UTC, yp-ivan commented on packages/client/src/pages/Game/setShipsPage.tsx
> +			<Footer className='footerPlacement footer'>
Лучше сначала писать основной класс, а затем все классы-модификаторы.
```suggestion
			<Footer className='footer footerPlacement'>
```

2023-04-14 15:20 UTC, yp-ivan commented on packages/client/src/pages/Game/style.css
> +.restShips p, .playersTurn p {
Один селектор в строку читается лучше.

2023-04-14 15:20 UTC, yp-ivan commented on packages/client/src/pages/Game/style.css
> +tbody tr :nth-child(2), tbody tr :nth-child(3) {
Думаю, nth-child легко заменить на class. Будет более универсальный код.

2023-04-14 15:20 UTC, yp-ivan commented on packages/client/src/pages/Game/style.css
Старайся сгруппировать стили. Между группами пустую строку для улучшения понимания.

2023-04-14 15:20 UTC, yp-ivan commented on packages/client/src/routers/index.tsx
> +// @ts-ignore
Лучше использовать вариант:
`// eslint-disable-next-line название_правила`

2023-04-14 15:20 UTC, yp-ivan commented on packages/client/src/utils/timer.tsx
> +interface Props {
```suggestion
type TProps {
```

2023-04-14 15:20 UTC, yp-ivan commented on packages/client/src/utils/timer.tsx
Может проще использовать объект Date с форматированием?

2023-04-14 16:47 UTC, JennJs commented on packages/client/src/utils/timer.tsx
> +let timerId: any;
![image](https://user-images.githubusercontent.com/106597506/232106528-66b6d3da-52c8-4c17-9f93-10c6ec432d4d.png)
тоже ошибка

2023-04-14 16:51 UTC, JennJs commented on packages/client/src/pages/500/index.tsx
окей, просто  увидела что импорты не в том порядке. На рефакторинг не тянет)

2023-04-14 18:53 UTC, Moriarty25 reviewed
Выглядит здорово!
Мне понравилась подсветка при надписи победа. Может стоит вынести её в mixin?)

2023-04-14 18:53 UTC, Moriarty25 commented on packages/client/src/pages/Game/Modals/modalGameover.tsx
> +					onClick={()=> navigate('/gameResults')}/>
еще лучше вынести в переменную goToGameResults
```suggestion
					onClick={goToGameResults}/>
```

2023-04-14 18:53 UTC, Moriarty25 commented on packages/client/src/pages/Game/gamePage.tsx
> +	const [gameAction, setGameActions] = useState(true);
```suggestion
	const [gameActions, setGameActions] = useState(true);
```

2023-04-14 18:53 UTC, Moriarty25 commented on packages/client/src/pages/Game/style.css
1.  Почему такое такое расширение? В остальном проекте используется scss, давайте придерживаться единообразия. 
2.  Почему именование классов в формате camelCase? 
3. Возможно стоит отказаться от хранения всех стилей в одном файле, это нарушает компонентный подход. (как минимум модальное окно - это отдельная сущность).
4. Использование scss в сочетании с БЭМ даст возможность лучше разделить стили на смысловые группы:
```
item {
 display: flex;

  &__title {
    margin: 0;
    padding: 0;
  }
}
```

2023-04-14 18:53 UTC, Moriarty25 commented on packages/client/src/pages/Game/style.css
> +	/*text-shadow: -1px 0 white, 0 1px white, 1px 0 white, 0 -1px white;*/
наверное, это лишнее)

2023-04-14 18:53 UTC, Moriarty25 commented on packages/client/src/pages/Game/style.css
> +	text-shadow: -6px 0 17px #006181, 0 1px 17px #006181, 1px 0 17px #006181, 0 -1px 17px #006181;
цвета лучше вынести в variables.scss

2023-04-14 18:53 UTC, Moriarty25 commented on packages/client/src/pages/Game/gameResultsPage.tsx
> +				onClick={() => navigate('/placement')}
И здесь PATHS

2023-04-14 18:53 UTC, Moriarty25 commented on packages/client/src/pages/Game/Modals/modalGameover.tsx
Модалка получилась хорошая, предлагаю ее вынести в общую папку compontents и прокидывать в нее содержимое через children, можно/нужно ее переиспользовать. Соответственно, стили тоже придется к ней вынести

2023-04-14 19:25 UTC, djpont approved these changes

2023-04-14 19:25 UTC, djpont commented on packages/client/src/pages/Game/Modals/modalGameover.tsx
> +					className='button buttonModalGameOver'
Тут можно стили написать для `. buttonsModalGameOver .button` или `. buttonsModalGameOver > button`, чтобе не прокидывать в компонент стили и сократить код

2023-04-14 19:25 UTC, djpont commented on packages/client/src/pages/Game/Modals/modalGameover.tsx
> +					onClick={()=> navigate('/gameResults')}/>
`'/gameResults'` нужно перенести в PATHS и импортировать

2023-04-14 19:25 UTC, djpont commented on packages/client/src/pages/Game/gamePage.tsx
> +		}, 4000);
4000 лучше вынести в отдельную константу, чтобы не было магического числа и если будет другой таймаут, то переиспользовать

2023-04-14 19:25 UTC, djpont commented on packages/client/src/pages/Game/setShipsPage.tsx
> +			<Footer className='footerPlacement footer'>
`footer` можно не прописывать, он там добавляется сам

2023-04-14 19:25 UTC, djpont commented on packages/client/src/pages/Game/setShipsPage.tsx
> +			<div className='buttonsContainer'>
Предлагаю использовать scss modules, названия классов неуникальные, могут всплыть проблемы с верткой из-за этого

2023-04-14 19:25 UTC, djpont commented on packages/client/src/routers/index.tsx
> +		element: <GameResultsPage/>,
В остальных местах название компонента странички начинается с Page, лучше единый стиль использовать

2023-04-14 19:25 UTC, djpont commented on packages/client/src/utils/timer.tsx
> +	}
Как-то заморочно. Может лучше хранить время в секундах.
А в `add()` сделать вычислять время. Но с точки зрения производительности так лучше, наверное.
Не критично в целом

2023-04-14 22:45 UTC, JennJs commented on packages/client/src/utils/timer.tsx
Мне было проще сделать таймер.  Лучше переделаю  после дедлайна уже

2023-04-15 05:00 UTC, yp-ivan approved these changes
В целом хорошо!

2023-04-15 05:04 UTC, yp-ivan commented on packages/client/src/pages/Game/PageGame/PageGame.tsx
> +						className= {whoseTurn === 1 ? ' playerName playerName1 turn'
className лучше вынести в отдельную переменную. В предыдущем review писал об этом (возможно пропустила). Если много комментариев по review, то средние сворачиваются.

2023-04-15 05:42 UTC, Moriarty25 commented on packages/client/src/pages/Game/Modals/components/modalGameover.tsx
> +			<div className='modalGameOverResult'>{props.result}</div>
Лучше деструктурировать пропсы

2023-04-15 08:30 UTC, JennJs commented on packages/client/src/pages/Game/PageGame/PageGame.tsx
> +						className= {whoseTurn === 1 ? ' playerName playerName1 turn'
точно, свернулись, не видела)

2023-04-15 08:31 UTC, JennJs commented on packages/client/src/pages/Game/gamePage.tsx
> +// @ts-ignore
это я забыла убрать просто

2023-04-15 08:44 UTC, JennJs commented on packages/client/src/pages/Game/gameResultsPage.tsx
> +	};
что-то я не нашла

2023-04-15 16:50 UTC, AntLer-24rus commented on packages/client/src/pages/500/index.tsx
Это очень даже хорошо что есть инициатива поправить что-то, в частности импорты. Однако соглашусь с @yp-ivan что это делается отдельно задачей. Для того чтобы не растерять по пути до рефакторинга все инициативы очень хорошей практикой будет на такие места создавать issues, в которых кратко описывать что не так. Их же потом будет довольно удобно "приклеять" к ПР который этот рефакторинг делает.

2023-04-15 18:16 UTC, AntLer-24rus requested changes
Отличная работа 🔥 Есть небольшие шероховатости которые нужно переделать, смотри комментарии. И хочу подчеркнуть, не отмахивайся от замечаний и наставлений сокомандников, я их тоже читаю 😺

2023-04-15 18:16 UTC, AntLer-24rus commented on packages/client/src/utils/timer.tsx
Поддерживаю @yp-ivan, все-таки лучше не изобретать велосипед. У вас же еще двух языковое приложение и формат даты да и времени будет зависеть от выбранной локали.

2023-04-15 18:16 UTC, AntLer-24rus commented on packages/client/src/utils/timer.tsx
> +			timerId = setTimeout(add, 1000);
`setInterval` тут предпочтительнее использовать, будет более точное время. Так как между вызовами `setTimeout` ты еще выполняешь свой код в том числе и рендер реакта.

2023-04-15 18:16 UTC, AntLer-24rus commented on packages/client/src/utils/timer.tsx
> +		<p id='timer'>{time}</p>
С какой целью используешь здесь id?

2023-04-16 05:43 UTC, IRGrekov approved these changes

2023-04-16 10:50 UTC, JennJs commented on packages/client/src/pages/Game/gameResultsPage.tsx
> +	const gameTime = '00:05:30';
здесь будет выводиться время игры, которое будет сохраняться в стор со страницы игры вместе со всей остальной статистикой игры.  А это заглушка пока.

2023-04-16 10:56 UTC, JennJs commented on packages/client/src/utils/timer.tsx
> +let timerId: NodeJS.Timer;
![image](https://user-images.githubusercontent.com/106597506/232302543-f69a9679-fde7-4b03-a1c4-35071759b6f9.png)
на тип number ругается

2023-04-16 11:00 UTC, JennJs commented on packages/client/src/utils/timer.tsx
> +		<p id='timer'>{time}</p>
я изначально пробовала вставить содержимое в <p> через textContent, потом решила через state, а id не убрала

2023-04-16 11:04 UTC, JennJs commented on packages/client/src/pages/Game/Modals/modalGameActions.tsx
это совсем другой компонент по виду и содержимому, это подсказки, всплывающие во время игры

2023-04-16 11:09 UTC, JennJs commented on packages/client/src/pages/Game/PageGameResults/styles.scss
> +}
да, все ряды должны быть одной высоты

2023-04-16 11:13 UTC, JennJs commented on packages/client/src/pages/Game/PageSetShips/PageSetShips.tsx
> +		console.log('поле очищено');
эта функция будет написана позже, а пока просто оставила, чтобы было какое-то оповещение

2023-04-16 12:43 UTC, djpont commented on packages/client/src/utils/timer.tsx
> +let timerId: NodeJS.Timer;
> Не согласен с типом. Браузерное API не знает что такое NodeJS.Timer. Id таймера в браузере просто `number`

Это я советовал NodeJS.Timer использовать, т.к. TS ругается на number:
TS2322: Type 'Timer' is not assignable to type 'number'.

2023-04-16 17:09 UTC, JennJs commented on packages/client/src/utils/timer.tsx
> +let timerId: NodeJS.Timer;
о том, что компонент будет вставлен несколько раз на странице я не подумала, потому что такого не предполагалось. Тогда переменную нельзя оставлять в глобальной области видимости

2023-04-16 18:15 UTC, JennJs commented on packages/client/src/components/Modal/modal.tsx
> +export const Modal: FC<TModalProps> = (props) => {
исправила, надеюсь проверки те, что ожидались)

2023-04-16 18:15 UTC, JennJs commented on packages/client/src/components/Modal/modal.tsx
> +			</div>
изначально не подумала про такой вариант, исправила

2023-04-16 21:39 UTC, JennJs commented on packages/client/src/components/Modal/modal.scss
не использовала потому что у меня и так вложенные стили по названию компонента, так что путаницы в названиях не должно было быть

2023-04-17 14:21 UTC, AntLer-24rus approved these changes
Все окей 😺

2023-04-17 14:21 UTC, AntLer-24rus commented on packages/client/src/components/Modal/modal.tsx
> +						<div className=' underlineBottom'></div>
```suggestion
						<div className='underlineBottom'></div>
```

2023-04-17 14:21 UTC, AntLer-24rus commented on packages/client/src/components/Modal/modal.tsx
> +						<div className=' underlineBottom'></div>
```suggestion
						<div className='underlineBottom'></div>
```

2023-04-17 14:21 UTC, AntLer-24rus commented on packages/client/src/components/timer/timerClass.ts
> +	private _timerId: NodeJS.Timer | undefined;
Для браузерного API:
```suggestion
	private _timerId: number | undefined;
```

2023-04-17 14:21 UTC, AntLer-24rus commented on packages/client/src/components/timer/timerClass.ts
> +		const seconds = (this._seconds % 60).toString().padStart(2, '0');
Отличное решение! 🔥

2023-04-17 14:37 UTC, merged