LUN-82: Научиться пересоздавать клиентское Redux-хранилище из серверного
Lunatics-yp/lunatics pull request #51
Opened 2023-05-08 16:58 UTC by JennJs

### Какую задачу решаем
initialState должен быть из стейта, который был на сервере.

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2023-05-08 18:28 UTC, djpont approved these changes

2023-05-08 18:28 UTC, djpont commented on packages/client/src/stores/store.ts
> +	}
А может собрать оба действия в одну проверку?
```
let preloadedState;
if (typeof window !== 'undefined') {
preloadedState = window.__PRELOADED_STATE__
delete window.__PRELOADED_STATE__;
}
```

2023-05-08 18:28 UTC, djpont commented on packages/client/ssr/ssr.tsx
> +	return [initialState, renderResult];
Возможно стоит возвращать не массивом, а объектом? Мне кажется объектом надёжнее, если вдруг ещё поля добавятся.

2023-05-08 18:31 UTC, yp-ivan approved these changes
Вроде всё хорошо.
Дал пару комментариев.

2023-05-08 18:31 UTC, yp-ivan commented on packages/client/src/stores/store.ts
> +	}
Немного запутанно.
Возможно лучше написать так:
```ts
	let preloadedState;

	if (typeof window !== 'undefined') {
		preloadedState = window.__PRELOADED_STATE__;
		delete window?.__PRELOADED_STATE__;
	}
```

2023-05-08 18:31 UTC, yp-ivan commented on packages/server/server.ts
> +				template = fs.readFileSync(path.resolve(distPath, 'index.html'), 'utf-8');
Возможно тут не надо было переформатировать код от Александра.

2023-05-09 10:52 UTC, JennJs commented on packages/server/server.ts
> +				template = fs.readFileSync(path.resolve(distPath, 'index.html'), 'utf-8');
тут я ничего не делала, может это его поздний коммит просто

2023-05-09 14:54 UTC, AntLer-24rus requested changes
Хорошая работа! Но немного не докрученная задача на мой взгляд, потому есть не большой архитектурный промах. Страшного ничего не вижу, ты молодец!! 🚀

2023-05-09 14:54 UTC, AntLer-24rus commented on packages/client/src/stores/store.ts
> +		delete window?.__PRELOADED_STATE__;
Думаю имеет смысл также удалять скрипт в html дереве который этот `__PRELOADED_STATE__` вам загрузил. Ну или не удалять ничего уже 🤷🏼‍♂️

2023-05-09 14:54 UTC, AntLer-24rus commented on packages/client/ssr/ssr.tsx
> +};
Стоит вернуть декларацию функции `render` к исходному виду, так как было у @djpont. Поясню почему: сейчас вы только инициализируете стор на  сервере, а в дальнейшем вам придется его заполнять и объект `store` понадобиться. Например нужно будет достать из базы юзера который уже авторизован (поняли это по наличию кук). Если оставить такой подход, то функция будет знать про существование базы и про то как к ней обращаться ну и т.д. нарушается принцип единой ответственности.

2023-05-09 14:54 UTC, AntLer-24rus commented on packages/server/server.ts
> +				)}</script>`;
```suggestion
      const stringifyState = JSON.stringify(initialState).replace(/</g, '\\u003c');
			const stateMarkup = `<script>window.__PRELOADED_STATE__ = ${stringifyState}</script>`;
```

Читается намного проще и не пришлось выключать правило линтера

2023-05-09 14:54 UTC, AntLer-24rus commented on packages/client/ssr/typing.ts
> +	}>;
У вас же вроде есть уже выведенный тип коневого хранилища `RootState` в файле `packages/client/src/stores/store.ts`, поправь меня если я что-то путаю

2023-05-10 14:07 UTC, JennJs commented on packages/client/ssr/typing.ts
> +	}>;
да есть, но выдавал ошибку с ним

2023-05-12 14:01 UTC, AntLer-24rus approved these changes
👌🏻👨🏼‍💻

2023-05-12 16:17 UTC, merged