Feature/lun 93 forum api
Lunatics-yp/lunatics pull request #60
Opened 2023-05-26 09:57 UTC by IRGrekov

2023-05-26 11:13 UTC, Moriarty25 commented
Скриншоты добавь)

2023-05-26 11:32 UTC, Moriarty25 commented on packages/client/src/components/images/Del/index.tsx
не очень хорошее название Del. Пиши полностью, приходится угадывать

2023-05-26 11:32 UTC, Moriarty25 commented on packages/client/src/config/api.ts
> +export const OAUTH_FORUM_URL = '/полный/путь';
почему OAUTH?

2023-05-26 11:32 UTC, Moriarty25 commented on packages/client/src/stores/reducers/forum/forumSlice.ts
> +					const forumData = action.payload as unknown as CreateForumResponseObj;
Тут явно что-то не так с типами

2023-05-26 11:32 UTC, Moriarty25 commented on packages/client/src/stores/reducers/forum/forumThunks.ts
> +// eslint-disable-next-line max-len
старайся не использовать такие выключатели линтера

2023-05-26 11:32 UTC, Moriarty25 commented on packages/client/src/stores/reducers/forum/forumThunks.ts
> +// eslint-disable-next-line max-len
лучше не выключать правила линта

2023-05-26 11:34 UTC, Moriarty25 commented on packages/client/src/api/request/index.ts
в своем ПР #58 тоже делал [второе окружение](https://github.com/Lunatics-yp/lunatics/pull/58/files#diff-4c78b6e235ec411e6b78e121ec095dfd9f201c42fe412d4d478b9aeb6497ac26)
@juliv какое оставляем?

2023-05-26 19:50 UTC, Moriarty25 commented on packages/client/src/api/forum.ts
> +	),
`data `- объект с полями `action: string` и `data: createForumRequestData`; 
Возникает вопрос нужно ли тип экшена для бэка передавать в параметрах? Разве недостаточно здесь указать его явно и передавать в `data` уже конкретные данные ` createForumRequestData`. Иначе придется потом где-то при вызове 'createForum' вместе с данными передать "forum.create".  
Мне кажется, нужно оставить это на уровне api. Это касается всех методов api ниже.

2023-05-26 19:50 UTC, Moriarty25 commented on packages/client/src/api/typingForum.ts
> +};
вот тут у нас с бэка приходит
 ```
{
    "data": {
        "id": 10,
        "name": "Название топика",
        "forum_id": 1,
        "user_id": 2,
        "created_at": 322323
    }
}
```
если оставить так, то оно потом также сохраниться в редакс и будет лишняя вложенность (из-за data: {}). 
Можно применить DTO (трансформер данных) и избавиться от этого. Плюс можно будет сразу переименовать, например,  `forum_id `в  `forumId`.
У нас уже есть трансформер `UserDTO`, можешь сделать аналогично. Сам трансформер можно применить передать сохранением в редакс. 
Аналогично с топиками и сообщениями.

2023-05-26 19:50 UTC, Moriarty25 commented on packages/client/src/components/images/Answer/index.tsx
> +/* eslint-disable max-len */
Можно было бы отформатировать с prettier и не выключать правило

2023-05-26 19:50 UTC, Moriarty25 commented on packages/client/src/components/images/Delete/index.tsx
> +/* eslint-disable max-len */
тут тоже можно отформатировать prettier

2023-05-26 19:50 UTC, Moriarty25 commented on packages/client/src/pages/Forum/ForumDiscussion/ForumDiscussionBox/ForumDiscussionBox.module.scss
> +@import "client/src/styles/app";
одинарные кавычки в остальных местах

2023-05-26 19:50 UTC, Moriarty25 commented on packages/client/src/pages/Forum/ForumDiscussion/ForumDiscussionBox/ForumDiscussionColumn/ForumDiscussionColumn.module.scss
> +@import "client/src/styles/app";
кавычки

2023-05-26 19:50 UTC, Moriarty25 commented on packages/client/src/pages/Forum/ForumTopic/Message/Message.module.scss
> +@import "client/src/styles/app";
кавычки

2023-05-26 19:50 UTC, Moriarty25 commented on packages/client/src/pages/Forum/ForumTopic/Message/Submassage/Message.module.scss
> +	&__retwit {
```suggestion
	&__retweet {
```

2023-05-26 19:50 UTC, Moriarty25 commented on packages/client/src/pages/Forum/ForumTopic/Message/Submassage/index.tsx
> +/* eslint-disable max-len */
выключи отключение правила и отформатируй файл, тут уже даже не svg. Неудобно же будет смотреть потом)

2023-05-26 19:50 UTC, Moriarty25 commented on packages/client/src/pages/Forum/ForumTopic/Message/index.tsx
> +/* eslint-disable max-len */
включи правило)

2023-05-26 19:50 UTC, Moriarty25 commented on packages/client/src/pages/Forum/ForumTopic/index.tsx
> +	console.log(selectedParent);
ненужный лог

2023-05-26 19:50 UTC, Moriarty25 commented on packages/client/src/pages/Forum/compontents/ForumColumn/index.tsx
> +
лишняя пустая строка

2023-05-26 19:50 UTC, Moriarty25 commented on packages/client/src/stores/reducers/forum/forumSlice.ts
> +/* eslint-disable max-len */
завязывай с этим)))

2023-05-26 19:50 UTC, Moriarty25 commented on packages/client/src/api/typingAPI.ts
> +  user_id: number;
наверно тогда старый `id: number` надо удалить? Или откуда у юзера два id?

2023-05-26 19:50 UTC, Moriarty25 commented on packages/client/src/pages/Leaderboard/index.tsx
лидерборд-то как сюда залетел?) Можно удалить из этого ПР

2023-05-26 19:50 UTC, Moriarty25 commented on packages/client/src/pages/Forum/ForumTopic/Message/index.tsx
> +		const newSubmassage = () => {
```suggestion
		const newSubMassage = () => {
```

2023-05-26 19:50 UTC, Moriarty25 commented on packages/client/src/stores/reducers/forum/forumSlice.ts
> +		//Форум
Вроде линтер должен ругаться, если после `//` нет пробела. Верни)

2023-05-26 19:50 UTC, Moriarty25 commented on packages/client/src/stores/reducers/forum/forumSlice.ts
> +		addSubmassage(state, {payload}: PayloadAction<{parentid: number; content: string}>) {
```suggestion
		addSubmassage(state, {payload}: PayloadAction<{parentId: number; content: string}>) {
```

2023-05-26 20:24 UTC, Moriarty25 commented on packages/client/src/components/images/Answer/Answer.scss
эти стили разве используются в этом компоненте?

2023-05-26 20:24 UTC, Moriarty25 commented on packages/client/src/components/images/Answer/typing.ts
Этот файл, кажется, тоже не отсюда

2023-05-26 20:24 UTC, Moriarty25 commented on packages/client/src/pages/Forum/ForumTopic/index.tsx
> +
лишняя пустая строка

2023-05-26 20:24 UTC, Moriarty25 commented on packages/client/src/pages/Forum/ForumTopic/Message/Submassage/typing.ts
> +export type TMessageProps = {
Разве должно быть не  TSubMessageProps?

2023-05-26 20:24 UTC, Moriarty25 commented on packages/client/src/pages/Forum/ForumTopic/Message/Submassage/Message.module.scss
Лучше изменить название файла в соответствии с названием компонента

2023-05-26 20:24 UTC, Moriarty25 commented on packages/client/src/pages/Forum/ForumTopic/Message/index.tsx
> +						))}
Можно не делать map в верстке и вынести в переменную. И для `key `лучше использовать `id`, а не `index`

2023-05-26 20:28 UTC, Moriarty25 commented on packages/client/src/pages/Forum/ForumTopic/Message/Submassage/index.tsx
> +export const Submassage = forwardRef<HTMLDivElement, TMessageProps>(
```suggestion
export const Submessage = forwardRef<HTMLDivElement, TMessageProps>(
```

2023-05-26 20:28 UTC, Moriarty25 commented on packages/client/src/pages/Forum/ForumTopic/Message/Submassage/index.tsx
> +export const Submassage = forwardRef<HTMLDivElement, TMessageProps>(
В названии папки такая же опечатка

2023-05-26 23:26 UTC, Moriarty25 commented on packages/client/src/api/typingForum.ts
> +};
Тут может вернуться ошибка, поэтому необходимо использовать `TErrorAPI`, который у нас для этого существует. 
Это относится ко всем Response

2023-05-26 23:26 UTC, Moriarty25 commented on packages/client/src/api/typingForum.ts
> +};
У нас же типы начинаются с приставки T: `TCreateForumRequest`
Смотри весь файлик.

2023-05-27 07:44 UTC, yp-ivan commented on packages/client/src/api/request/index.ts
@Moriarty25 Можно твоё оставить.
У Романа добавляется ещё одна сущность (со своим baseURL для форума).

2023-05-27 09:33 UTC, yp-ivan reviewed
Общие замечания:
- постараться убрать `/* eslint-disable max-len */` (думаю, можно везде он них избавиться, максимум оставить с суффиксом `-next-line`)
- Не забывать писать названия типов TS с буквы `T`
- Не отключать lint'ы

2023-05-27 09:33 UTC, yp-ivan commented on .hintrc
Не совсем ясно, нужен ли этот файл в этом PR.

2023-05-27 12:10 UTC, IRGrekov commented on lefthook.yml
Проблемы с stylelint были из-за этого включал. Исправлю

2023-05-27 12:23 UTC, IRGrekov commented on packages/client/src/stores/reducers/forum/forumThunks.ts
> +// eslint-disable-next-line max-len
Убрал их

2023-05-27 12:24 UTC, IRGrekov commented on packages/client/src/api/typingForum.ts
> +  data: object;
так в документации написан запрос список форумов

2023-05-27 12:25 UTC, IRGrekov commented on packages/client/src/components/images/Answer/index.tsx
> +/* eslint-disable max-len */
На этом устройстве отключено было, да пофикшу

2023-05-27 12:25 UTC, IRGrekov commented on packages/client/src/pages/Forum/ForumDiscussion/ForumDiscussionBox/ForumDiscussionBox.module.scss
> +@import "client/src/styles/app";
На этом устройстве у меня редактор автоматически меняет ковычки, да исправлю везде

2023-05-27 12:26 UTC, IRGrekov commented on packages/client/src/stores/reducers/forum/forumSlice.ts
> +/* eslint-disable max-len */
Да буду, отходит от этого, понял

2023-05-27 14:02 UTC, Moriarty25 commented on packages/client/src/api/typingForum.ts
> +  data: object;
там пустой объект должен быть, а `object` немногим лучше `any`

2023-05-28 17:27 UTC, AntLer-24rus requested changes
Видел рекомендовали в комментариях расширение на vscode [`spel checker`](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker) не пренебрегай рекомендацией, очень годное расширение!

И второй момент есть стойкое ощущение что автоматика у тебя не отрабатывает. Проверь что prettyer включен.

Есть еще замечания на типизацию в файлике `forumSlice.ts` проверь пожалуйста.

В целом огромная работы, ты большой молодец!!! 🚀🔥 Думаю замечания не составит труда поправить!

2023-05-28 17:27 UTC, AntLer-24rus commented on packages/client/src/pages/Forum/compontents/ForumColumn/index.tsx
> +				{/* //	<button>Удалить</button> */}
Не стоит тащить в кодовую базу логику в комментариях. Либо оформить это как-то более внятно. С побуждением удалить этот комментарий когда логика будет реализована, даже если в планах реализовывать ее тебе.

2023-05-28 17:27 UTC, AntLer-24rus commented on packages/client/src/pages/Leaderboard/index.tsx
> +
лишние пустые строки

2023-05-28 17:27 UTC, AntLer-24rus commented on packages/client/src/pages/MainMenu/pages/main/index.tsx
> +					// disabled={!user}
Смотри коммент выше про логику в коментариях.

2023-05-28 17:27 UTC, AntLer-24rus commented on packages/client/src/stores/reducers/forum/forumSlice.ts
> +		//Форум
++

2023-05-28 17:27 UTC, AntLer-24rus commented on packages/client/src/stores/reducers/forum/forumSlice.ts
> +			});
Голову сломал пока понял что форматирование съехало....

2023-05-28 17:27 UTC, AntLer-24rus commented on packages/client/src/stores/reducers/forum/forumSlice.ts
> +					const forumData = action.payload as unknown as TCreateForumResponseObj;
TS говорит что у тебя `patload` будет такой `AxiosResponse<TCreateForumResponse, any> & TUserDTO`

Что-то тут явно не сходится....

2023-05-28 17:27 UTC, AntLer-24rus commented on packages/client/src/stores/reducers/forum/forumSlice.ts
> +			const {parentid, content} = payload;
```suggestion
		addSubmessage(state, {payload}: PayloadAction<{parentId: number; content: string}>) {
			const {parentId, content} = payload;
```

2023-05-28 17:27 UTC, AntLer-24rus commented on packages/client/src/stores/reducers/forum/forumSlice.ts
> +							});
форматирование

2023-05-28 17:27 UTC, AntLer-24rus commented on packages/client/src/stores/reducers/forum/forumSlice.ts
> +				const topicData = action.payload as unknown as TCreateTopicResponseObj;
Аналогичная история с типами

2023-05-28 17:27 UTC, AntLer-24rus commented on packages/client/src/stores/reducers/forum/forumSlice.ts
> +					const messageData = action.payload as unknown as TCreateMessageResponseObj;
смотри комменты выше.

2023-05-28 17:27 UTC, AntLer-24rus commented on packages/client/src/stores/reducers/forum/forumThunks.ts
> +			return await forumdAPI.createForum(data);
здесь и ниже в этом фале в аналогичных местах `await` можно опустить

2023-05-28 17:27 UTC, AntLer-24rus commented on packages/client/src/stores/reducers/forum/forumThunks.ts
> +};
Форматирование, есть стойкое ощущение что prettier не работает...

2023-05-28 17:27 UTC, AntLer-24rus commented on packages/client/src/stores/reducers/forum/typing.ts
> +	parentid?: number;
```suggestion
	parentId?: number;
```

2023-05-30 19:58 UTC, IRGrekov commented on packages/client/src/config/api.ts
> +export const FORUM_URL = '/полный/путь';
Пока это абстрактный путь просто

2023-05-30 19:59 UTC, IRGrekov commented on packages/client/src/pages/Forum/ForumTopic/Message/Submessage/index.tsx
> +				<span className={styles.message__date}>23 мар 2023 в 21:31</span>
Это захардкожено было, не менял. В бэке пока нету поля с временем

2023-05-30 20:00 UTC, IRGrekov commented on packages/client/src/pages/Forum/ForumTopic/Message/index.tsx
>  						<span className={styles.message__date}>23 мар 2023 в 21:31</span>
Пока что да

2023-05-30 20:02 UTC, IRGrekov commented on packages/client/src/stores/reducers/forum/forumSlice.ts
> +					const forumData = action.payload as unknown as TCreateForumResponseObj;
по итогу тут  Там должен быть тип PayloadAction<TForums>, но не смог пофиксить. Таже проблема была в прошлом спринте с форумом

2023-05-30 20:03 UTC, IRGrekov commented on packages/client/src/pages/Forum/ForumDiscussion/ForumDiscussionBox/ForumDiscussionColumn/index.tsx
>  	return (
Не понял, что ты имел ввиду, отступ?

2023-06-01 04:06 UTC, yp-ivan reviewed
Добавил комментарии по большей части форматирования и eslint (их можно быстро исправить).

2023-06-01 04:06 UTC, yp-ivan commented on packages/client/src/stores/reducers/forum/forumThunks.ts
> +export const forumThunks = {getAllForums, createForum, createTopic,getAllTopics, createMessage, getAllMessages};
У всех функций выше можно убрать export, так как они напрямую нигде в коде не используются, а только через `forumThunks`.

2023-06-01 09:16 UTC, IRGrekov commented on packages/client/src/api/typingForum.ts
> +  data: TCreateTopicResponseObj;
Да так понятней будет исправил

2023-06-01 09:24 UTC, IRGrekov commented on packages/client/src/api/typingForum.ts
Действительно странно, пофиксил

2023-06-01 09:27 UTC, IRGrekov commented on packages/client/src/pages/Forum/ForumDiscussion/ForumDiscussionBox/ForumDiscussionColumn/index.tsx
> +			<Link to={`${name}`}>
...images/Delete/index.tsx удалил файл, ведь не используется в проекте

2023-06-01 09:32 UTC, IRGrekov commented on packages/client/src/stores/reducers/forum/forumSlice.ts
> +	parentMessages: (state: RootState) => state.forumReducer.messages.filter(m => !m.parent_message_id),
Исправил в файле

2023-06-01 09:39 UTC, Moriarty25 commented on packages/client/src/api/forum.ts
> +		apiForum.post<TCreateForumResponse>(FORUM_URL, data)
```suggestion
		apiForum.post<TCreateForumResponse>(FORUM_URL, {
			action: 'нужный_тип',
			data: data,
		}),
```
Писал об этом в прошлый раз. Думаю, это было бы очень удобно. Типы экшенов для форума можно вынести в enum.

2023-06-01 12:40 UTC, AntLer-24rus commented on packages/client/src/stores/reducers/forum/forumSlice.ts
> +				const forumData = action.payload.data as unknown as TCreateForumResponseData;
Плохая практика так каставать типы, не допусти привычки ее использовать! Лучше разберись как всетаки обойти это место правильно!

2023-06-22 15:18 UTC, merged